# Generated by Django 4.0.2 on 2022-12-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceCrew',
            fields=[
                ('crew_id', models.IntegerField(primary_key=True, serialize=False)),
                ('crew_rep', models.CharField(blank=True, max_length=255, null=True)),
                ('task', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'maintenance_crew',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaintenanceWork',
            fields=[
                ('maintenance_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_maintained', models.DateField(blank=True, null=True)),
                ('maintenance_condition', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'maintenance_work',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('train_id', models.IntegerField(primary_key=True, serialize=False)),
                ('train_model', models.CharField(blank=True, max_length=255, null=True)),
                ('train_maxspeed', models.IntegerField()),
                ('no_of_seats', models.IntegerField()),
                ('no_of_toilets', models.IntegerField(blank=True, null=True)),
                ('reclining_seats', models.IntegerField(blank=True, null=True)),
                ('luggage_storage', models.IntegerField(blank=True, null=True)),
                ('folding_tables', models.IntegerField(blank=True, null=True)),
                ('vending_machines', models.IntegerField(blank=True, null=True)),
                ('disability_access', models.IntegerField(blank=True, null=True)),
                ('food_service', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'train',
                'managed': False,
            },
        ),
    ]
