# Generated by Django 4.0.2 on 2022-12-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nodes',
            fields=[
                ('node_id', models.IntegerField(db_column='node_ID', primary_key=True, serialize=False)),
                ('connected_station_id_1', models.IntegerField(blank=True, db_column='connected_station_ID_1', null=True)),
                ('connected_station_1_duration', models.IntegerField(blank=True, null=True)),
                ('connected_station_id_2', models.IntegerField(blank=True, db_column='connected_station_ID_2', null=True)),
                ('connected_station_2_duration', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nodes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.IntegerField(primary_key=True, serialize=False)),
                ('route_start', models.CharField(blank=True, max_length=30, null=True)),
                ('route_end', models.CharField(blank=True, max_length=30, null=True)),
                ('route_cost', models.IntegerField()),
                ('route_duration', models.CharField(max_length=30)),
                ('route_type', models.CharField(max_length=10)),
                ('one_way', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'route',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.IntegerField(db_column='station_ID', primary_key=True, serialize=False)),
                ('station_name', models.CharField(blank=True, max_length=100, null=True)),
                ('train_system', models.CharField(blank=True, max_length=30, null=True)),
                ('one_way', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'station',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StationRoutes',
            fields=[
                ('station_routes_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'station_routes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrainSystem',
            fields=[
                ('train_system_id', models.IntegerField(db_column='train_system_ID', primary_key=True, serialize=False)),
                ('system_name', models.CharField(blank=True, max_length=100, null=True)),
                ('system_type', models.CharField(blank=True, max_length=30, null=True)),
                ('train_system_cost', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'train_system',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TripTrainSystem',
            fields=[
                ('train_trip_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'trip_train_system',
                'managed': False,
            },
        ),
    ]
