# Generated by Django 4.0.2 on 2022-12-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainDate',
            fields=[
                ('date_id', models.IntegerField(primary_key=True, serialize=False)),
                ('trip_sched', models.DateField()),
            ],
            options={
                'db_table': 'train_date',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.IntegerField(db_column='trip_ID', primary_key=True, serialize=False)),
                ('trip_departure', models.DateTimeField()),
                ('trip_arrival', models.DateTimeField()),
                ('trip_duration', models.CharField(max_length=30)),
                ('trip_cost', models.IntegerField()),
                ('trip_origin', models.CharField(max_length=30)),
                ('trip_destination', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'trip',
                'managed': False,
            },
        ),
    ]
