# Generated by Django 4.0.2 on 2022-12-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_initial', models.CharField(max_length=5)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_no', models.IntegerField(primary_key=True, serialize=False)),
                ('date_purchased', models.DateField()),
                ('ticket_cost', models.IntegerField()),
            ],
            options={
                'db_table': 'ticket',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TicketTrip',
            fields=[
                ('ticket_trip_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ticket_trip',
                'managed': False,
            },
        ),
    ]
